### ISSUE TITLE
php 7.2 > not work on your package

### ISSUE THREAD

**Issue by pyaeswin** [kevinsandow/PBEWithMD5AndDES#6]
Hello,

Can you update with php 7.2 > 

Thanks

**Comment by pengzhile** [comment]
> Hello,
> 
> Can you update with php 7.2 >
> 
> Thanks

Try this: https://github.com/pengzhile/PBEWithMD5AndDES

**Comment by kevinsandow** [comment]
It's been a while, but with some motivation and spare time during the holidays I also updated my repository.
